parameters:
    kopjra_guzzle.log_subscriber: Kopjra\GuzzleBundle\EventListener\LogSubscriber
    kopjra_guzzle.oauth_subscriber: Kopjra\GuzzleBundle\Subscribers\OAuthSubscriber
    kopjra_guzzle.cache_subscriber: Kopjra\GuzzleBundle\Subscribers\CacheSubscriber
    kopjra_guzzle.cache_subscriber: Kopjra\GuzzleBundle\Subscribers\CacheSubscriber
    kopjra_guzzle.retry_subscriber: Kopjra\GuzzleBundle\Subscribers\RetrySubscriber
    kopjra_guzzle.services: Kopjra\GuzzleBundle\Services\Services

services:
    guzzle:
        class: GuzzleHttp\Client
        arguments: ['']
    kopjra.guzzle_bundle.twig.guzzle_extension:
        class: Kopjra\GuzzleBundle\Twig\GuzzleExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments: ['@guzzle']
    kopjra.guzzle_bundle.event_listener.emitter:
        class: Kopjra\GuzzleBundle\EventListener\Emitter
        public: false
    kopjra.guzzle_bundle.event_listener.log_subscriber:
        class: %kopjra_guzzle.log_subscriber%
        public: false
        tags:
            - { name: guzzle.subscriber }
        arguments: ['@logger']
    kopjra.guzzle.oauth:
        class: %kopjra_guzzle.oauth_subscriber%
        tags:
           - { name: guzzle.subscriber }
    kopjra.guzzle.cache:
        class: %kopjra_guzzle.cache_subscriber%
        tags:
           - { name: guzzle.subscriber }
    kopjra.guzzle.retry:
        class: %kopjra_guzzle.retry_subscriber%
        tags:
           - { name: guzzle.subscriber }
    kopjra.guzzle.services:
        class: %kopjra_guzzle.services%
        arguments: ['@knp_gaufrette.filesystem_map']