<?php
namespace Kopjra\GuzzleBundle\Tests\Types;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:57:03.
 */
class UrlTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UrlType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \stdClass();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kopjra\GuzzleBundle\Types\UrlType::convertToPHPValue
     * @todo   Implement testConvertToPHPValue().
     */
    public function testConvertToPHPValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Types\UrlType::convertToDatabaseValue
     * @todo   Implement testConvertToDatabaseValue().
     */
    public function testConvertToDatabaseValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Types\UrlType::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Types\UrlType::getSQLDeclaration
     * @todo   Implement testGetSQLDeclaration().
     */
    public function testGetSQLDeclaration()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Types\UrlType::__toString
     * @todo   Implement test__toString().
     */
    public function testToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
