<?php
namespace Kopjra\GuzzleBundle\Tests\DependencyInjection\Compiler;

use Kopjra\GuzzleBundle\Tests\AppKernel;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:50:01.
 */
class EventsCompilerPassTest extends \PHPUnit_Framework_TestCase {
    /**
     * @covers Kopjra\GuzzleBundle\DependencyInjection\Compiler\EventsCompilerPass::process
     */
    public function testProcess() {
        $kernel = new AppKernel('test', true);
        $kernel->boot();
    }
}
