<?php
namespace Kopjra\GuzzleBundle\Tests\DependencyInjection\Compiler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:50:01.
 */
class EventsCompilerPassTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var EventsCompilerPass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \stdClass();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kopjra\GuzzleBundle\DependencyInjection\Compiler\EventsCompilerPass::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
