<?php
namespace Kopjra\GuzzleBundle\Tests\Subscribers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:54:17.
 */
class CacheSubscriber extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CacheSubscriber
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \stdClass();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\CacheSubscriber::getEvents
     * @todo   Implement testGetEvents().
     */
    public function testGetEvents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\CacheSubscriber::attach
     * @todo   Implement testAttach().
     */
    public function testAttach()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\CacheSubscriber::onBefore
     * @todo   Implement testOnBefore().
     */
    public function testOnBefore()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\CacheSubscriber::onComplete
     * @todo   Implement testOnComplete().
     */
    public function testOnComplete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\CacheSubscriber::onError
     * @todo   Implement testOnError().
     */
    public function testOnError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\CacheSubscriber::getCacheType
     * @todo   Implement testGetCacheType().
     */
    public function testGetCacheType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\CacheSubscriber::setCacheType
     * @todo   Implement testSetCacheType().
     */
    public function testSetCacheType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
