<?php
namespace Kopjra\GuzzleBundle\Tests\Subscribers;

use Kopjra\GuzzleBundle\Tests\AppKernel;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:54:49.
 */
class OAuthSubscriberTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Symfony\Component\HttpKernel\Kernel
     */
    private $kernel;

    /**
     * {@inheritdoc}
     */
    protected function setUp() {
        $this->kernel = new AppKernel('KopjraGuzzleExtensionTest', true);
        $this->kernel->boot();
    }

    public function testService() {
        $container = $this->kernel->getContainer();

        $this->assertTrue($container->has('kopjra.guzzle.subscribers.oauth'));
        $this->assertInstanceOf('GuzzleHttp\\Event\\SubscriberInterface', $container->get('kopjra.guzzle.subscribers.oauth'));
    }
}
