<?php
namespace Kopjra\GuzzleBundle\Tests\Subscribers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:55:19.
 */
class RetrySubscriberTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RetrySubscriber
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \stdClass();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::config
     * @todo   Implement testConfig().
     */
    public function testConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::exponentialDelay
     * @todo   Implement testExponentialDelay().
     */
    public function testExponentialDelay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::getEvents
     * @todo   Implement testGetEvents().
     */
    public function testGetEvents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::onComplete
     * @todo   Implement testOnComplete().
     */
    public function testOnComplete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::createChainFilter
     * @todo   Implement testCreateChainFilter().
     */
    public function testCreateChainFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::createIdempotentFilter
     * @todo   Implement testCreateIdempotentFilter().
     */
    public function testCreateIdempotentFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::createStatusFilter
     * @todo   Implement testCreateStatusFilter().
     */
    public function testCreateStatusFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::createLoggingDelay
     * @todo   Implement testCreateLoggingDelay().
     */
    public function testCreateLoggingDelay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::createCurlFilter
     * @todo   Implement testCreateCurlFilter().
     */
    public function testCreateCurlFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Subscribers\RetrySubscriber::createConnectFilter
     * @todo   Implement testCreateConnectFilter().
     */
    public function testCreateConnectFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
