<?php
namespace Kopjra\GuzzleBundle\Tests\Twig;

use GuzzleHttp\Client;
use Kopjra\GuzzleBundle\Twig\GuzzleExtension;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:56:07.
 */
class GuzzleExtensionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Kopjra\GuzzleBundle\Twig\GuzzleExtension
     */
    protected $TwigGuzzleExtension;
    /**
     * @var \GuzzleHttp\Client
     */
    protected $client;

    public function setUp() {
        $this->client = new Client();
        $this->TwigGuzzleExtension = new GuzzleExtension($this->client);
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::__construct
     */
    public function testGuzzleExtension(){
        $this->assertInstanceOf(
            'Twig_ExtensionInterface',
            $this->TwigGuzzleExtension
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getFilters
     */
    public function testGetFilters() {
        $filters = $this->TwigGuzzleExtension->getFilters();
        $this->assertTrue(is_array($filters));
        $this->assertInstanceOf('Twig_SimpleFilter', $filters[0]);
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getTests
     */
    public function testGetTests() {
        $tests = $this->TwigGuzzleExtension->getTests();
        $this->assertTrue(is_array($tests));
        $this->assertInstanceOf('Twig_SimpleTest', $tests[0]);
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getFunctions
     */
    public function testGetFunctions() {
        $functions = $this->TwigGuzzleExtension->getFunctions();
        $this->assertTrue(is_array($functions));
        $this->assertInstanceOf('Twig_SimpleFunction', $functions[0]);
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getGlobals
     */
    public function testGetGlobals() {
        $globals = $this->TwigGuzzleExtension->getGlobals();
        $this->assertTrue(is_array($globals));
        $this->assertArrayHasKey('guzzle', $globals);
        $this->assertEquals($this->client, $globals['guzzle']);
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getName
     */
    public function testGetName() {
        $this->assertEquals('kopjra.guzzle_bundle.twig.guzzle_extension', $this->TwigGuzzleExtension->getName());
    }
}
