<?php
namespace Kopjra\GuzzleBundle\Tests\Twig;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:56:07.
 */
class GuzzleExtensionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GuzzleExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \stdClass();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getFilters
     * @todo   Implement testGetFilters().
     */
    public function testGetFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getTests
     * @todo   Implement testGetTests().
     */
    public function testGetTests()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getFunctions
     * @todo   Implement testGetFunctions().
     */
    public function testGetFunctions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getGlobals
     * @todo   Implement testGetGlobals().
     */
    public function testGetGlobals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Twig\GuzzleExtension::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
