framework:
  csrf_protection:
    enabled: true
  default_locale: en
  form:
    csrf_protection:
      field_name: _t
    enabled: true
  fragments:
    enabled: true
    path: /_f
  http_method_override: true
  router:
    resource: '%kernel.root_dir%/config/routing.yml'
    strict_requirements: null
  secret: null
  session: null
  templating:
    engines:
    - twig
  translator: null
  trusted_hosts: null
  trusted_proxies: null
  validation:
    enable_annotations: true

knp_gaufrette:
  adapters:
    webservices:
      local:
        directory: '%kernel.root_dir%/Webservices'
  filesystems:
    webservices:
      adapter: webservices

kopjra_guzzle:
  client:
    connect_timeout: 15
    decode_content: gzip
    headers:
      Accept-Charset: 'utf-8'
      Content-Transfer-Encoding: 'binary'
      User-Agent: '%user_agent%'
    timeout: 15
    verify: '%kernel.root_dir%/Resources/cacert.cer'

  subscribers:
    oauth:
      consumer_key: key
      consumer_secret: secret
      signature_method: HMAC-SHA1

parameters:
  kernel.secret: null

services:
  logger:
    arguments:
    - '%kernel.cache_dir%'
    class: Kopjra\GuzzleBundle\Tests\Resources\Fixtures\FileLogger

twig:
  debug: '%kernel.debug%'
  form:
    resources:
    - form_div_layout.html.twig
  globals:
    main:
      id: doctrine_cache.providers.main
    metrics:
      id: doctrine_cache.providers.metrics
  strict_variables: '%kernel.debug%'
