<?php
namespace Kopjra\GuzzleBundle\Tests\Manager;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-13 at 15:53:06.
 */
class ServicesManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ServicesManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \stdClass();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kopjra\GuzzleBundle\Manager\ServicesManager::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Manager\ServicesManager::attach
     * @todo   Implement testAttach().
     */
    public function testAttach()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kopjra\GuzzleBundle\Manager\ServicesManager::setFilesystem
     * @todo   Implement testSetFilesystem().
     */
    public function testSetFilesystem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
